name: Build and Test Configuration
description: a composite that builds hibridons then tests it for a given configuration
# This is a composite action that runs on the same runner as the main workflow.
# Schema: https://json.schemastore.org/github-action.json

# Runs on the same runner and same work area as the main workflow.
# No need to use 'build artifacts' to share files with the main workflow.
# Env variables are inherited.
# Secrets are not available -- must be passed explicitly as inputs or env vars.

inputs:
  build_type:
    required: false
    type: string
    default: "debug"  # other options: "release", "code_coverage", "profiling"
  compiler:
    required: false
    type: string
    default: "gfortran"
  os:
    required: false
    type: string
    default: "debian-12"
  test_suite:   # test suite
    required: true
    type: string
    default: "quick"
runs:
  using: 'composite'
  steps:
  - name: Set up environment
    shell: bash # Must explicitly specify the shell for each step.
    run: |
      echo "Setting up environment variables for ${{inputs.build_type}} with ${{inputs.compiler}}"
      CMAKE_BUILD_PARALLEL_LEVEL="1" # disable parallel builds
      CTEST_OUTPUT_ON_FAILURE="ON" # This way we don't need a flag to ctest
      CTEST_PARALLEL_LEVEL="1"
      OMP_NUM_THREADS="2"

      # Disable address sanitizer's memory leak detection in release builds
      if [ "${{inputs.build_type}}" == 'release' ]
      then
        ASAN_OPTIONS="detect_leaks=0"
      else
        ASAN_OPTIONS="detect_leaks=1"
      fi
      
      # LINK_TIME_OPTIMIZATION not operational on debian9 gfortran (gfortran is too old : /usr/bin/ar: CMakeFiles/hib.dir/ancou.F90.o: plugin needed to handle lto object)
      LINK_TIME_OPTIMIZATION="OFF"

      # ENABLE_UNINIT_VAR_RUNTIME_DETECTOR works on ubuntu 20.04 but causes some tests to fail on debian 9:
      # AddressSanitizer: FPE on unknown address 0x7f329c9bc3f8 (pc 0x7f329c9bc3f8 bp 0x6290000baf00 sp 0x7ffc8d5cf650 T0)
      # 0 0x7f329c9bc3f7 in ATL_dtrsmKR_rk4 (/usr/lib/libatlas.so.3+0x10a3f7))
      if [ "${{inputs.build_type}}" == 'debug' ]
      then
        ENABLE_UNINIT_VAR_RUNTIME_DETECTOR=ON
      else
        ENABLE_UNINIT_VAR_RUNTIME_DETECTOR=OFF
      fi

      # export the environment variables for use in next steps
      echo CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL} >> $GITHUB_ENV
      echo CTEST_OUTPUT_ON_FAILURE=${CTEST_OUTPUT_ON_FAILURE} >> $GITHUB_ENV
      echo CTEST_PARALLEL_LEVEL=${CTEST_PARALLEL_LEVEL} >> $GITHUB_ENV
      echo OMP_NUM_THREADS=${OMP_NUM_THREADS} >> $GITHUB_ENV
      echo ASAN_OPTIONS=${ASAN_OPTIONS} >> $GITHUB_ENV
      echo LINK_TIME_OPTIMIZATION=${LINK_TIME_OPTIMIZATION} >> $GITHUB_ENV
      echo ENABLE_UNINIT_VAR_RUNTIME_DETECTOR=${ENABLE_UNINIT_VAR_RUNTIME_DETECTOR} >> $GITHUB_ENV
  - name: Configure CMake
    shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
    run: |
      echo "configuring cmake with options: ${{inputs.build_type}} ${{inputs.compiler}} ${{inputs.os}} ${{inputs.test_suite}} "
      mkdir -p ${{github.workspace}}/build && \
      CMAKE_BUILD_TYPE=''
      ENABLE_CODE_COVERAGE='OFF'
      ENABLE_PROFILING='OFF'
      case "${{inputs.build_type}}" in
        debug)
          CMAKE_BUILD_TYPE=Debug
          ;;
        release)
          CMAKE_BUILD_TYPE=Release
          ;;
        code_coverage)
          CMAKE_BUILD_TYPE=Debug
          ENABLE_CODE_COVERAGE='ON'
          ;;
        profiling)
          CMAKE_BUILD_TYPE=Release
          ENABLE_PROFILING='ON'
          ;;
        *)
          echo "Unknown build type: ${{inputs.build_type}}"
          exit 1
      esac
      CMAKE_OPTIONS=""
      if [ "${{inputs.compiler}}" == 'ifort' ]
      then
        if [ "${{inputs.os}}" == 'debian-12' ]
        then
          module load compilers/ifort/latest
        elif [ "${{inputs.os}}" == 'macos-11.2' ]
        then
          source /opt/intel/oneapi/setvars.sh --force
        fi
        CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_VENDOR=Intel10_64lp"
        FORTRAN_COMPILER=ifort
      elif [ "${{inputs.compiler}}" == 'gfortran' ]
      then
        if [ "${{inputs.os}}" == 'debian-12' ]
        then
          FORTRAN_COMPILER=gfortran-12
        elif [ "${{inputs.os}}" == 'macos-11.2' ]
        then
          FORTRAN_COMPILER=gfortran-11
          CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_VENDOR=Apple"
        else
          echo "Unknown os: ${{inputs.os}}"
          exit 1
        fi
      else
        echo "Unknown compiler: ${{inputs.compiler}}"
        exit 1
      fi
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBUILD_TESTING=ON"
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DENABLE_CODE_COVERAGE=${ENABLE_CODE_COVERAGE}"
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DENABLE_PROFILING=${ENABLE_PROFILING}"
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DCMAKE_Fortran_COMPILER=${FORTRAN_COMPILER}"
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DLINK_TIME_OPTIMIZATION=${{env.LINK_TIME_OPTIMIZATION}}"
      CMAKE_OPTIONS="${CMAKE_OPTIONS} -DENABLE_UNINIT_VAR_RUNTIME_DETECTOR=${{env.ENABLE_UNINIT_VAR_RUNTIME_DETECTOR}}"
      echo "CMAKE_OPTIONS: $CMAKE_OPTIONS"
      cmake -B ${{github.workspace}}/build $CMAKE_OPTIONS

  - name: Build
    shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
    run: |
      if [ "${{inputs.compiler}}" == 'ifort' ]
      then
        if [ "${{inputs.os}}" == 'debian-12' ]
        then
          module load compilers/ifort/latest
        elif [ "${{inputs.os}}" == 'macos-11.2' ]
        then
          source /opt/intel/oneapi/setvars.sh --force
        fi
      fi
      if [ "${{inputs.os}}" == 'debian-12' ] && [ "${{inputs.compiler}}" == 'gfortran' ]
      then
        # build with zwcheck.py to ensure zero warnings policy
        unbuffer cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}} > >(tee ${{github.workspace}}/build/make.stdout) 2> >(tee ${{github.workspace}}/build/make.stderr >&2)
        ${{github.workspace}}/bin/zwcheck.py --make-stdout ${{github.workspace}}/build/make.stdout --show-warnings 'true'
      else
        # build without zwcheck.py because:
        # - unbuffer command is not available on macos
        # - zwcheck.py only works with gfortran at the moment
        cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}}
      fi
  - name: Show failure details
    shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
    run: |
      if [ "${{inputs.compiler}}" == 'ifort' ]
      then
        if [ "${{inputs.os}}" == 'debian-12' ]
        then
          module load compilers/ifort/latest
        elif [ "${{inputs.os}}" == 'macos-11.2' ]
        then
          source /opt/intel/oneapi/setvars.sh --force
        fi
      fi
      if [ "${{inputs.os}}" == 'debian-12' ] && [ "${{inputs.compiler}}" == 'gfortran' ]
      then
        # build with zwcheck.py to ensure zero warnings policy
        unbuffer cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}} --verbose > >(tee ${{github.workspace}}/build/make.stdout) 2> >(tee ${{github.workspace}}/build/make.stderr >&2)
        ${{github.workspace}}/bin/zwcheck.py --make-stdout ${{github.workspace}}/build/make.stdout --show-warnings 'true'
      else
        # build without zwcheck.py because:
        # - unbuffer command is not available on macos
        # - zwcheck.py only works with gfortran at the moment
        cmake --build ${{github.workspace}}/build --config ${{inputs.build_type}} --verbose
      fi
    if: failure()

  - name: Make sure no code coverage metrics files exist before running tests
    if: ${{ inputs.build_type == 'code_coverage' }}
    shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
    working-directory: ${{github.workspace}}/build
    run: |
      make clean_coverages

  - name: Install profiling tools
    if: ${{ inputs.build_type == 'profiling' }}
    shell: bash # Must explicitly specify the shell for each step.
    working-directory: ${{github.workspace}}/build
    run: |
      python3 -m venv ./profiling.venv && \
      source ./profiling.venv/bin/activate && \
      pip install --upgrade pip && \
      pip install gprof2dot

  - name: Test
    shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
    working-directory: ${{github.workspace}}/build
    run: |
      if [ "${{inputs.build_type}}" == 'profiling' ]
      then
        source ./profiling.venv/bin/activate
      fi
      if [ "${{inputs.compiler}}" == 'ifort' ]
      then
        if [ "${{inputs.os}}" == 'debian-12' ]
        then
          module load compilers/ifort/latest
        elif [ "${{inputs.os}}" == 'macos-11.2' ]
        then
          source /opt/intel/oneapi/setvars.sh --force
        fi
      fi
      if [ "${{inputs.test_suite}}" == 'all' ]
      then
        ctest --parallel --output-on-failure
      else
        ctest --parallel --output-on-failure -L "^${{inputs.test_suite}}$"
      fi
  - name: Create Code Coverage Report
    if: ${{ inputs.build_type == 'code_coverage' }}
    shell: bash # Must explicitly specify the shell for each step. https://github.com/orgs/community/discussions/18597
    working-directory: ${{github.workspace}}/build
    run: |
      make html_coverages
      