name: Reusable workflow

# May run on a different runner than the main workflow.
# Must use 'build artifacts' to share files with the main workflow.
# Env variables are not inherited.

on:
  workflow_call:
    inputs:
      reusable_input:
        description: 'Input to the reusable workflow'
        required: true
        type: string
      filename:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  reusable-workflow-job:
    runs-on: debian-12
    # Map the job output(s) to step output(s)
    steps:
      - name: Process reusable input
        id: process-step
        env:
          HELLO_WORLD_SECRET: "do-not-tell-anyone"
        run: |
          echo "reusable_input=${{ inputs.reusable_input }}"
          echo "HELLO_WORLD_SECRET=${HELLO_WORLD_SECRET}"
      - name: Process file
        run: |
          echo "Processing file: ${{ inputs.filename }}"
          echo "file processed" >> ${{ inputs.filename }}
