name: Hibridon continuous integration  

# builds, runs and tests hibridon in multiple configurations (see https://github.com/hibridon/hibridon/issues/102)
# (it should cover main risks for main platform types) and its runners are expected to be always available to ensure pull requests and pushes are always validated in time.
on:
  pull_request:
    branches: [ master ]     # run basic ci on pull requests on master
  push:
    branches: [ master ]     # run basic ci on pushes on master
  schedule:
    - cron:  '0 02 * * 1'    # run full ci Every mondays at 00:02
env:
  CMAKE_BUILD_PARALLEL_LEVEL: "1" # disable parallel builds
  CTEST_OUTPUT_ON_FAILURE: "ON" # This way we don't need a flag to ctest
  CTEST_PARALLEL_LEVEL: "1"
  OMP_NUM_THREADS: "2"
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [debian-12, macos-11.2]
        build_type: [Debug, Release]
        compiler: [gfortran, ifort]
    env:
      ASAN_OPTIONS: "detect_leaks=${{ matrix.build_type == 'Release' && '0' || '1' }}" # Disable address sanitizer's memory leak detection in release builds
      # LINK_TIME_OPTIMIZATION not operational on debian9 gfortran (gfortran is too old : /usr/bin/ar: CMakeFiles/hib.dir/ancou.F90.o: plugin needed to handle lto object)
      LINK_TIME_OPTIMIZATION: "OFF"

      # ENABLE_UNINIT_VAR_RUNTIME_DETECTOR works on ubuntu 20.04 but causes some tests to fail on debian 9:
      # AddressSanitizer: FPE on unknown address 0x7f329c9bc3f8 (pc 0x7f329c9bc3f8 bp 0x6290000baf00 sp 0x7ffc8d5cf650 T0)
      # 0 0x7f329c9bc3f7 in ATL_dtrsmKR_rk4 (/usr/lib/libatlas.so.3+0x10a3f7))
      ENABLE_UNINIT_VAR_RUNTIME_DETECTOR: ${{ matrix.build_type == 'Debug' && 'ON' || 'OFF' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        mkdir -p ${{github.workspace}}/build && \
        CMAKE_OPTIONS=""
        if [ "${{matrix.compiler}}" == 'ifort' ]
        then
          CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBLA_VENDOR=Intel10_64lp"
          FORTRAN_COMPILER=ifort
          if [ "${{matrix.os}}" == 'debian-12' ]
          then
            module load compilers/ifort/latest
          fi
        elif [ "${{matrix.compiler}}" == 'gfortran' ]
        then
          if [ "${{matrix.os}}" == 'debian-12' ]
          then
            FORTRAN_COMPILER=gfortran-12
          elif [ "${{matrix.os}}" == 'macos-11.2' ]
          then
            FORTRAN_COMPILER=gfortran-11
          else
            echo "Unknown os: ${{matrix.os}}"
            exit 1
          fi
        else
          echo "Unknown compiler: ${{matrix.compiler}}"
          exit 1
        fi
        CMAKE_OPTIONS="${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}"
        CMAKE_OPTIONS="${CMAKE_OPTIONS} -DBUILD_TESTING=ON"
        CMAKE_OPTIONS="${CMAKE_OPTIONS} -DCMAKE_Fortran_COMPILER=${FORTRAN_COMPILER}"
        CMAKE_OPTIONS="${CMAKE_OPTIONS} -DLINK_TIME_OPTIMIZATION=${{env.LINK_TIME_OPTIMIZATION}}"
        CMAKE_OPTIONS="${CMAKE_OPTIONS} -DENABLE_UNINIT_VAR_RUNTIME_DETECTOR=${{env.ENABLE_UNINIT_VAR_RUNTIME_DETECTOR}}"
        cmake -B ${{github.workspace}}/build $CMAKE_OPTIONS

    - name: Build
      run: |
        if [ "${{matrix.compiler}}" == 'ifort' ]
        then
          if [ "${{matrix.os}}" == 'debian-12' ]
          then
            module load compilers/ifort/latest
          fi
        fi
        if [ "${{matrix.os}}" == 'debian-12' ] && [ "${{matrix.compiler}}" == 'gfortran' ]
        then
          # build with zwcheck.py to ensure zero warnings policy
          unbuffer cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} > >(tee ${{github.workspace}}/build/make.stdout) 2> >(tee ${{github.workspace}}/build/make.stderr >&2)
          ${{github.workspace}}/bin/zwcheck.py --make-stdout ${{github.workspace}}/build/make.stdout --show-warnings 'true'
        else
          # build without zwcheck.py because:
          # - unbuffer command is not available on macos
          # - zwcheck.py only works with gfortran at the moment
          cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
        fi
    - name: catch build fail
      run: |
        if [ "${{matrix.compiler}}" == 'ifort' ]
        then
          if [ "${{matrix.os}}" == 'debian-12' ]
          then
            module load compilers/ifort/latest
          fi
        fi
        if [ "${{matrix.os}}" == 'debian-12' ] && [ "${{matrix.compiler}}" == 'gfortran' ]
        then
          # build with zwcheck.py to ensure zero warnings policy
          unbuffer cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --verbose > >(tee ${{github.workspace}}/build/make.stdout) 2> >(tee ${{github.workspace}}/build/make.stderr >&2)
          ${{github.workspace}}/bin/zwcheck.py --make-stdout ${{github.workspace}}/build/make.stdout --show-warnings 'true'
        else
          # build without zwcheck.py because:
          # - unbuffer command is not available on macos
          # - zwcheck.py only works with gfortran at the moment
          cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --verbose
        fi
      if: failure()

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        if [ "${{matrix.compiler}}" == 'ifort' ]
        then
          if [ "${{matrix.os}}" == 'debian-12' ]
          then
            module load compilers/ifort/latest
          fi
        fi
        TEST_SUITE=''
        if [ "${{github.event_name}}" == 'pull_request' ]
        then
          TEST_SUITE='coverage'
        elif [ "${{github.event_name}}" == 'push' ]
        then
          TEST_SUITE='coverage'
        elif [ "${{github.event_name}}" == 'schedule' ]
        then
          TEST_SUITE=''  # run all tests
        fi
        if [ "${TEST_SUITE}" == '' ]
        then
          ctest --parallel --output-on-failure
        else
          ctest --parallel --output-on-failure -L '^$TEST_SUITE$
        fi
