name: Hibridon continuous integration  

# builds, runs and tests hibridon in multiple configurations (see https://github.com/hibridon/hibridon/issues/102)
# (it should cover main risks for main platform types) and its runners are expected to be always available to ensure pull requests and pushes are always validated in time.
on:
  pull_request:
    branches: [ master ]     # run basic ci on pull requests on master
  push:
    branches: [ master ]     # run basic ci on pushes on master
  schedule:
    - cron:  '0 02 * * 1'    # run full ci Every mondays at 00:02
env:
  CMAKE_BUILD_PARALLEL_LEVEL: "1" # disable parallel builds
  CTEST_OUTPUT_ON_FAILURE: "ON" # This way we don't need a flag to ctest
  CTEST_PARALLEL_LEVEL: "1"
  OMP_NUM_THREADS: "2"
jobs:
  main_job:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [debian-12, macos-11.2]
          build_type: [Debug, Release]
          compiler: [gfortran, ifort]
    steps:
      - name: Call build_and_test
        uses: ./.github/workflows/lib/build_and_test.yml
        with:
          build_type: ${{ matrix.build_type }}
          compiler: ${{ matrix.compiler }}
          os: ${{ matrix.os }}
  
