name: Long CI on macOS-11.2

on:
  schedule:
    - cron:  '0 02 * * 1'    # Every mondays at 00:02
env:
  CTEST_OUTPUT_ON_FAILURE: "ON" # This way we don't need a flag to ctest
  OMP_NUM_THREADS: "2"
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.2]
        build_type: [Debug, Release]
        compiler: [gfortran-11, ifort]
        #library: [Apple, Intel10_64lp]
        library: [Intel10_64lp]
    env:
      FC: ${{ matrix.compiler }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure CMake
      run: |
        source /opt/intel/oneapi/setvars.sh --force
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_TESTING=ON -DCMAKE_Fortran_COMPILER=${{ matrix.compiler }} -DBLA_VENDOR=${{matrix.library}}

    - name: Build
      run: |
        source /opt/intel/oneapi/setvars.sh --force
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: catch build fail
      run: |
        source /opt/intel/oneapi/setvars.sh --force
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --verbose
      if: failure()

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        source /opt/intel/oneapi/setvars.sh --force
        ctest --output-on-failure
