name: Run with reusable workflow

on:
    pull_request:
        branches: [ master ]     # run basic ci on pull requests on master

defaults:
  run:
    shell: bash

jobs:
  job-1:
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [debian-12, macos-11.2]
          build_type: [Debug, Release]
          compiler: [gfortran, ifort]
    steps:
      - name: Print Hello World
        run: echo "Hello World ${{ matrix.compiler }} on ${{ matrix.os }} with ${{ matrix.build_type }}"
      - name: Create a file
        run: echo "Hello World" > input.txt

  job-2:
    needs: job-1
    uses: ./.github/workflows/build_and_test.yml # We do not need to check out the repository to use the reusable workflow
    with:
      reusable_input: "job-2-input"
      filename: "input.txt"
